server:
  port: 8081
spring:
  application:
    name: dm-increment
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.239.2:5432/dm
    username: dm
    password: hzmcdm

swagger:
  show: true

logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error